name = "Gaming"

[[data]]
name = "Install Deckify"
description = "Installs Deckify, a tool for managing Steam Deck configurations"
script = "deckify-setup.sh"
task_list = "FM"

[[data]]
name = "Install Decky Plugin Loader"
description = "Installs Decky Loader, a plugin manager for Steam Deck"
script = "decky-plugin-loader-install.sh"
task_list = "FM"

[[data]]
name = "Install Sunshine"
description = "Installs Sunshine, a self-hosted game streaming server"
script = "sunshine.sh"
task_list = "FM"

[[data]]
name = "Remove Decky Plugin Loader"
description = "Removes Decky Loader from Steam Deck"
script = "decky-plugin-loader-remove.sh"
task_list = "FM"
