name = "Gaming"

[[data]]
name = "Install Deckify"
description = "Installs Deckify, a tool for managing Steam Deck configurations"
script = "deckify-setup.sh"
task_list = "FM"

[[data]]
name = "Install Decky Plugin Loader"
description = "Installs Decky Loader, a plugin manager for Steam Deck"
script = "decky-plugin-loader-install.sh"
task_list = "FM"

[[data]]
name = "Install Sunshine"
description = "Installs Sunshine, a self-hosted game streaming server"
script = "sunshine.sh"
task_list = "FM"

[[data]]
name = "Remove Decky Plugin Loader"
description = "Removes Decky Loader from Steam Deck"
script = "decky-plugin-loader-remove.sh"
task_list = "FM"

[[data]]
name = "Emulators"

[[data.entries]]
name = "Blastem"
description = "A Genesis emulator. NO Games are included"
script = "emulators/sega/blastem.sh"
task_list = "FM"

# [[data.entries]]
# name = "Yabause"
# description = "A Sega Saturn emulator"
# script = "emulators/sega/yabause.sh"
# task_list = "FM"

[[data.entries]]
name = "bsnes"
description = "Super Nintendo Emulator. NO Games are included"
script = "emulators/nintendo/bsnes.sh"
task_list = "FM"

[[data.entries]]
name = "Dolphin Emulator"
description = "GameCube and Wii Emulator. NO Games are included"
script = "emulators/nintendo/dolphin-emu.sh"
task_list = "FM"

[[data.entries]]
name = "Flycast"
description = "A Dreamcase emulator. NO Games are included"
script = "emulators/sega/flycast.sh"
task_list = "FM"

[[data.entries]]
name = "Gopher 64"
description = "N64 Emulator. NO Games are included"
script = "emulators/nintendo/gopher64.sh"
task_list = "FM"

[[data.entries]]
name = "Kronos"
description = "A Sega Saturn emulator. NO Games are included"
script = "emulators/sega/kronos.sh"
task_list = "FM"

[[data.entries]]
name = "MelonDS"
description = "Nintendo DS and DSi Emulator. NO Games are included"
script = "emulators/nintendo/melonds.sh"
task_list = "FM"

[[data.entries]]
name = "mGBA"
description = "Nintendo Game Boy Advance Emulator. NO Games are included"
script = "emulators/nintendo/mgba.sh"
task_list = "FM"

[[data.entries]]
name = "Mupen 64 Plus"
description = "N64 Emulator. NO Games are included"
script = "emulators/nintendo/mupen64plus.sh"
task_list = "FM"

[[data.entries]]
name = "PCSX2"
description = "A Playstation 2 emulator. NO Games or Bios' are included"
script = "emulators/playstation/pcsx2.sh"
task_list = "FM"

[[data.entries]]
name = "Play!"
description = "An Experimental Playstation 2 emulator. NO Games or Bios' are included"
script = "emulators/playstation/play-emu.sh"
task_list = "FM"

[[data.entries]]
name = "RetroArch Game Emulator"
description = "Frontend for emulators, game engines and media players. NO Games or Bios' are included"
script = "emulators/retroarch.sh"
task_list = "FM"

[[data.entries]]
name = "RPCS3"
description = "A Playstation 3 emulator. NO Games or Bios' are included"
script = "emulators/playstation/rpcs3.sh"
task_list = "FM"

[[data.entries]]
name = "Ryujinx"
description = "Nintendo Switch emulator. NO Games are included"
script = "emulators/nintendo/ryujinx.sh"
task_list = "FM"

# [[data.entries]]
# name = "PCSX"
# description = "A Playstation emulator. NO Games or Bios' are included"
# script = "emulators/playstation/pcsx.sh"
# task_list = "FM"

[[data.entries]]
name = "snes9x"
description = "Super Nintendo Emulator. NO Games are included"
script = "emulators/nintendo/snes9x.sh"
task_list = "FM"

[[data.entries]]
name = "XEMU"
description = "An Original Xbox emulator. NO Games or Bios' are included"
script = "emulators/xbox/xemu.sh"
task_list = "FM"

[[data.entries]]
name = "Xenia"
description = "An Experimental Xbox 360 emulator. NO Games or Bios' are included"
script = "emulators/xbox/xenia.sh"
task_list = "FM"
