#!/usr/bin/env bash
set -e

. ../../common-script.sh

# ---- Hardware detection ----

CPU_VENDOR=""
GPU_VENDOR=""
IS_MOBILE=false

detectHardware() {
    printf "%b\n" "${CYAN}Detecting hardware...${RC}"

    if grep -q "GenuineIntel" /proc/cpuinfo; then
        CPU_VENDOR="intel"
    elif grep -q "AuthenticAMD" /proc/cpuinfo; then
        CPU_VENDOR="amd"
    else
        printf "%b\n" "${RED}Unknown CPU vendor. Cannot proceed.${RC}"
        exit 1
    fi

    CPU_MODEL=$(grep "model name" /proc/cpuinfo | head -1 | cut -d':' -f2 | xargs)
    printf "%b\n" "${CYAN}CPU: ${CPU_MODEL}${RC}"

    if [ -f /sys/class/power_supply/BAT0/type ] || [ -f /sys/class/power_supply/BAT1/type ]; then
        IS_MOBILE=true
        printf "%b\n" "${CYAN}System type: Mobile / Laptop${RC}"
    else
        printf "%b\n" "${CYAN}System type: Desktop${RC}"
    fi

    if lspci 2>/dev/null | grep -qi "nvidia"; then
        GPU_VENDOR="nvidia"
    elif lspci 2>/dev/null | grep -qi "Advanced Micro Devices\|AMD\|Radeon" | grep -qi "VGA\|3D\|Display" 2>/dev/null || \
         lspci 2>/dev/null | grep -i "VGA\|3D\|Display" | grep -qi "AMD\|Radeon"; then
        GPU_VENDOR="amd"
    fi

    if [ -n "$GPU_VENDOR" ]; then
        GPU_MODEL=$(lspci 2>/dev/null | grep -i "VGA\|3D\|Display" | head -1 | sed 's/.*: //')
        printf "%b\n" "${CYAN}GPU: ${GPU_MODEL}${RC}"
    else
        printf "%b\n" "${YELLOW}No supported discrete GPU detected.${RC}"
    fi
}

# ---- Intel CPU undervolting via intel-undervolt ----

installIntelUndervolt() {
    if command_exists intel-undervolt; then
        printf "%b\n" "${GREEN}intel-undervolt is already installed.${RC}"
        return 0
    fi

    printf "%b\n" "${YELLOW}Installing intel-undervolt...${RC}"
    case "$PACKAGER" in
        pacman)
            "$AUR_HELPER" -S --needed --noconfirm intel-undervolt
            ;;
        apt-get | nala)
            "$ESCALATION_TOOL" "$PACKAGER" install -y git build-essential
            TMPDIR=$(mktemp -d)
            cd "$TMPDIR"
            git clone --depth=1 https://github.com/kitsunyan/intel-undervolt.git
            cd intel-undervolt
            ./configure
            make
            "$ESCALATION_TOOL" make install
            cd "$HOME"
            rm -rf "$TMPDIR"
            ;;
        dnf)
            "$ESCALATION_TOOL" "$PACKAGER" install -y git gcc make
            TMPDIR=$(mktemp -d)
            cd "$TMPDIR"
            git clone --depth=1 https://github.com/kitsunyan/intel-undervolt.git
            cd intel-undervolt
            ./configure
            make
            "$ESCALATION_TOOL" make install
            cd "$HOME"
            rm -rf "$TMPDIR"
            ;;
        *)
            printf "%b\n" "${RED}Package manager '${PACKAGER}' is not supported for intel-undervolt.${RC}"
            return 1
            ;;
    esac
}

configureIntelUndervolt() {
    printf "%b\n" "${YELLOW}Configuring Intel undervolting (safe defaults shown)...${RC}"
    printf "%b\n" "${YELLOW}Higher values = more aggressive undervolt. Start low and increase if stable.${RC}"
    printf "%b\n" ""

    printf "%b" "${CYAN}CPU core undervolt offset in mV (default 80, range 0-200): ${RC}"
    read -r cpu_offset
    cpu_offset=${cpu_offset:-80}

    printf "%b" "${CYAN}CPU Cache undervolt offset in mV (default 80): ${RC}"
    read -r cache_offset
    cache_offset=${cache_offset:-80}

    printf "%b" "${CYAN}iGPU undervolt offset in mV (default 50, use 0 if no iGPU): ${RC}"
    read -r igpu_offset
    igpu_offset=${igpu_offset:-50}

    CONFIG="/etc/intel-undervolt.conf"
    "$ESCALATION_TOOL" tee "$CONFIG" > /dev/null << EOF
# intel-undervolt configuration
# Generated by linutil undervolt script
# Modify values and run: sudo intel-undervolt apply

undervolt 0 'CPU' -${cpu_offset}
undervolt 1 'GPU' -${igpu_offset}
undervolt 2 'CPU Cache' -${cache_offset}
undervolt 3 'System Agent' 0
undervolt 4 'Analog I/O' 0
EOF

    printf "%b\n" "${GREEN}Configuration written to ${CONFIG}${RC}"
    "$ESCALATION_TOOL" intel-undervolt apply
    "$ESCALATION_TOOL" systemctl enable --now intel-undervolt.service
    printf "%b\n" "${GREEN}Intel undervolting applied and enabled on boot.${RC}"
}

setupIntelCPU() {
    installIntelUndervolt && configureIntelUndervolt || {
        printf "%b\n" "${RED}Intel undervolt setup failed.${RC}"
        return 1
    }
}

# ---- AMD CPU ----

setupAMDDesktopEPP() {
    printf "%b\n" "${CYAN}Configuring AMD pstate energy-performance preference...${RC}"

    if [ -f /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver ]; then
        PSTATE_DRIVER=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver)
        printf "%b\n" "${CYAN}Active frequency driver: ${PSTATE_DRIVER}${RC}"
    fi

    EPP_PATH="/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference"
    if [ ! -f "$EPP_PATH" ]; then
        printf "%b\n" "${YELLOW}AMD pstate EPP not available on this system.${RC}"
        printf "%b\n" "${YELLOW}For desktop undervolting, use BIOS/UEFI Curve Optimizer (PBO2).${RC}"
        return 0
    fi

    printf "%b\n" "${CYAN}Available EPP modes: $(cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences 2>/dev/null)${RC}"
    printf "%b" "${CYAN}Choose EPP mode (default: balance_performance): ${RC}"
    read -r epp_mode
    epp_mode=${epp_mode:-balance_performance}

    for cpu_epp in /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference; do
        echo "$epp_mode" | "$ESCALATION_TOOL" tee "$cpu_epp" > /dev/null 2>&1 || true
    done
    printf "%b\n" "${GREEN}Set EPP to '${epp_mode}' for all CPU cores.${RC}"

    "$ESCALATION_TOOL" tee /etc/udev/rules.d/99-cpu-epp.rules > /dev/null << EOF
ACTION=="add", SUBSYSTEM=="cpu", ATTR{cpufreq/energy_performance_preference}="${epp_mode}"
EOF
    printf "%b\n" "${GREEN}EPP setting made persistent via udev rule.${RC}"
}

installRyzenadj() {
    if command_exists ryzenadj; then
        printf "%b\n" "${GREEN}ryzenadj is already installed.${RC}"
        return 0
    fi

    printf "%b\n" "${YELLOW}Installing ryzenadj...${RC}"
    case "$PACKAGER" in
        pacman)
            "$AUR_HELPER" -S --needed --noconfirm ryzenadj
            ;;
        apt-get | nala)
            "$ESCALATION_TOOL" "$PACKAGER" install -y git cmake build-essential libpci-dev
            TMPDIR=$(mktemp -d)
            cd "$TMPDIR"
            git clone --depth=1 https://github.com/FlyGoat/RyzenAdj.git
            cd RyzenAdj
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make
            "$ESCALATION_TOOL" make install
            cd "$HOME"
            rm -rf "$TMPDIR"
            ;;
        dnf)
            "$ESCALATION_TOOL" "$PACKAGER" install -y git cmake gcc pciutils-devel
            TMPDIR=$(mktemp -d)
            cd "$TMPDIR"
            git clone --depth=1 https://github.com/FlyGoat/RyzenAdj.git
            cd RyzenAdj
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make
            "$ESCALATION_TOOL" make install
            cd "$HOME"
            rm -rf "$TMPDIR"
            ;;
        *)
            printf "%b\n" "${RED}Package manager '${PACKAGER}' is not supported for ryzenadj.${RC}"
            return 1
            ;;
    esac
}

setupAMDMobile() {
    installRyzenadj || return 1

    printf "%b\n" "${CYAN}AMD mobile CPU power tuning via ryzenadj.${RC}"
    printf "%b\n" "${YELLOW}Lower TDP values reduce heat and power draw while maintaining boost performance.${RC}"
    printf "%b\n" ""

    printf "%b" "${CYAN}STAPM (sustained power) limit in watts (default: 15): ${RC}"
    read -r stapm
    stapm=${stapm:-15}

    printf "%b" "${CYAN}Fast (short boost) limit in watts (default: 20): ${RC}"
    read -r fast_limit
    fast_limit=${fast_limit:-20}

    stapm_mw=$((stapm * 1000))
    fast_mw=$((fast_limit * 1000))

    "$ESCALATION_TOOL" ryzenadj \
        --stapm-limit="${stapm_mw}" \
        --fast-limit="${fast_mw}" \
        --slow-limit="${stapm_mw}"

    "$ESCALATION_TOOL" tee /etc/systemd/system/ryzenadj-limits.service > /dev/null << EOF
[Unit]
Description=RyzenAdj CPU Power Limits
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/ryzenadj --stapm-limit=${stapm_mw} --fast-limit=${fast_mw} --slow-limit=${stapm_mw}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

    "$ESCALATION_TOOL" systemctl daemon-reload
    "$ESCALATION_TOOL" systemctl enable ryzenadj-limits.service
    printf "%b\n" "${GREEN}AMD mobile power limits applied and enabled on boot.${RC}"
}

setupAMDCPU() {
    if [ "$IS_MOBILE" = "true" ]; then
        setupAMDMobile
    else
        setupAMDDesktopEPP
    fi
}

# ---- NVIDIA GPU ----

setupNvidiaGPU() {
    printf "%b\n" "${CYAN}Configuring NVIDIA GPU power limit...${RC}"

    if ! command_exists nvidia-smi; then
        printf "%b\n" "${RED}nvidia-smi not found. Please install NVIDIA drivers first.${RC}"
        return 1
    fi

    MAX_POWER=$(nvidia-smi --query-gpu=power.max_limit --format=csv,noheader,nounits 2>/dev/null | head -1 | xargs)
    MIN_POWER=$(nvidia-smi --query-gpu=power.min_limit --format=csv,noheader,nounits 2>/dev/null | head -1 | xargs)
    CUR_POWER=$(nvidia-smi --query-gpu=power.default_limit --format=csv,noheader,nounits 2>/dev/null | head -1 | xargs)

    if [ -z "$MAX_POWER" ]; then
        printf "%b\n" "${RED}Could not query NVIDIA GPU power limits.${RC}"
        return 1
    fi

    SUGGESTED=$(awk "BEGIN {printf \"%.0f\", ${MAX_POWER} * 0.85}")
    printf "%b\n" "${CYAN}Power limits — Current: ${CUR_POWER}W | Min: ${MIN_POWER}W | Max: ${MAX_POWER}W${RC}"
    printf "%b" "${CYAN}Enter desired power limit in watts (default: ${SUGGESTED}W = 85% of max): ${RC}"
    read -r power_limit
    power_limit=${power_limit:-$SUGGESTED}

    "$ESCALATION_TOOL" nvidia-smi -pm 1
    "$ESCALATION_TOOL" nvidia-smi --power-limit="$power_limit"

    "$ESCALATION_TOOL" tee /etc/systemd/system/nvidia-powerlimit.service > /dev/null << EOF
[Unit]
Description=NVIDIA GPU Power Limit
After=nvidia-persistenced.service

[Service]
Type=oneshot
ExecStart=/usr/bin/nvidia-smi -pm 1
ExecStart=/usr/bin/nvidia-smi --power-limit=${power_limit}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

    "$ESCALATION_TOOL" systemctl daemon-reload
    "$ESCALATION_TOOL" systemctl enable nvidia-powerlimit.service
    printf "%b\n" "${GREEN}NVIDIA power limit set to ${power_limit}W and persisted on boot.${RC}"
}

# ---- AMD GPU ----

installCoreCtrl() {
    printf "%b\n" "${YELLOW}Installing CoreCtrl...${RC}"
    case "$PACKAGER" in
        pacman)
            "$AUR_HELPER" -S --needed --noconfirm corectrl
            ;;
        apt-get | nala)
            "$ESCALATION_TOOL" "$PACKAGER" install -y corectrl 2>/dev/null || {
                printf "%b\n" "${YELLOW}corectrl not in repos, trying Flatpak...${RC}"
                checkFlatpak
                flatpak install -y flathub org.corectrl.CoreCtrl
            }
            ;;
        dnf)
            "$ESCALATION_TOOL" "$PACKAGER" install -y corectrl 2>/dev/null || {
                printf "%b\n" "${YELLOW}corectrl not in repos, trying Flatpak...${RC}"
                checkFlatpak
                flatpak install -y flathub org.corectrl.CoreCtrl
            }
            ;;
        *)
            printf "%b\n" "${YELLOW}Trying Flatpak for CoreCtrl...${RC}"
            checkFlatpak
            flatpak install -y flathub org.corectrl.CoreCtrl
            ;;
    esac

    # Allow CoreCtrl to control GPU without password prompt
    "$ESCALATION_TOOL" tee /etc/polkit-1/rules.d/90-corectrl.rules > /dev/null << 'EOF'
polkit.addRule(function(action, subject) {
    if ((action.id == "org.corectrl.helper.init" ||
         action.id == "org.corectrl.helperkiller.init") &&
        subject.local == true &&
        subject.active == true &&
        subject.isInGroup("wheel") ||
        subject.isInGroup("sudo")) {
            return polkit.Result.YES;
    }
});
EOF

    printf "%b\n" "${GREEN}CoreCtrl installed. Launch it to configure AMD GPU voltage curves.${RC}"
}

setupAMDGPU() {
    printf "%b\n" "${CYAN}Configuring AMD GPU...${RC}"

    CARD=""
    for card_path in /sys/class/drm/card*; do
        if [ -f "${card_path}/device/pp_od_clk_voltage" ]; then
            CARD="$card_path"
            break
        fi
    done

    if [ -z "$CARD" ]; then
        printf "%b\n" "${YELLOW}AMD GPU OD voltage interface not found on this card.${RC}"
    else
        printf "%b\n" "${CYAN}Current GPU voltage/frequency state:${RC}"
        cat "${CARD}/device/pp_od_clk_voltage"
        printf "%b\n" ""
    fi

    printf "%b\n" "${YELLOW}AMD GPU undervolting is best managed via CoreCtrl (GUI tool).${RC}"
    printf "%b" "${CYAN}Install CoreCtrl for AMD GPU voltage control? [Y/n]: ${RC}"
    read -r install_cc
    install_cc=${install_cc:-Y}

    if [ "$install_cc" = "y" ] || [ "$install_cc" = "Y" ]; then
        installCoreCtrl
    fi
}

# ---- Main ----

main() {
    checkEnv
    checkEscalationTool

    detectHardware

    printf "%b\n" ""
    printf "%b\n" "${CYAN}=== CPU Undervolting ===${RC}"
    case "$CPU_VENDOR" in
        intel) setupIntelCPU ;;
        amd)   setupAMDCPU   ;;
        *)     printf "%b\n" "${RED}Unsupported CPU vendor.${RC}" ;;
    esac

    printf "%b\n" ""
    printf "%b\n" "${CYAN}=== GPU Undervolting ===${RC}"
    case "$GPU_VENDOR" in
        nvidia) setupNvidiaGPU ;;
        amd)    setupAMDGPU    ;;
        *)      printf "%b\n" "${YELLOW}No supported GPU found, skipping GPU setup.${RC}" ;;
    esac

    printf "%b\n" ""
    printf "%b\n" "${GREEN}=== Undervolt setup complete! ===${RC}"
    printf "%b\n" "${YELLOW}Test system stability (run a stress test or play a game).${RC}"
    printf "%b\n" "${YELLOW}If you get crashes or artifacts, reduce the undervolt offset.${RC}"
}

main
