# Flatpak Restore Script
# Generated on Do 15. Jan 01:00:00 CET 2026
flatpak remote-add --if-not-exists --user "flathub" "https://flathub.org/repo/flathub.flatpakrepo"
flatpak remote-add --if-not-exists --user "webkit-sdk" "http://software.igalia.com/webkit-sdk-repo/" --title="WebKit Developer SDK"
flatpak remote-add --if-not-exists --user "fedora" "oci+https://registry.fedoraproject.org" --title="Fedora"
flatpak remote-add --if-not-exists --user "appcenter" "https://flatpak.elementary.io/repo.flatpakrepo"
flatpak install --assumeyes --user flathub "app.grayjay.Grayjay"
flatpak install --assumeyes --user flathub "com.bktus.gpgfrontend"
flatpak install --assumeyes --user flathub "com.cassidyjames.butler"
flatpak install --assumeyes --user flathub "com.github.LongSoft.UEFITool"
flatpak install --assumeyes --user flathub "com.github.LongSoft.UEFITool"
flatpak install --assumeyes --user flathub "com.github.finefindus.eyedropper"
flatpak install --assumeyes --user flathub "com.github.iwalton3.jellyfin-media-player"
flatpak install --assumeyes --user flathub "com.github.phase1geo.minder"
flatpak install --assumeyes --user flathub "com.github.tchx84.Flatseal"
flatpak install --assumeyes --user flathub "com.google.EarthPro"
flatpak install --assumeyes --user flathub "com.ktechpit.torrhunt"
flatpak install --assumeyes --user flathub "com.mattjakeman.ExtensionManager"
flatpak install --assumeyes --user flathub "com.openwall.John"
flatpak install --assumeyes --user flathub "com.ranfdev.DistroShelf"
flatpak install --assumeyes --user flathub "com.rtosta.zapzap"
flatpak install --assumeyes --user flathub "com.stremio.Stremio"
flatpak install --assumeyes --user flathub "dev.lizardbyte.app.Sunshine"
flatpak install --assumeyes --user flathub "io.github.ronniedroid.concessio"
flatpak install --assumeyes --user flathub "io.github.theforceengine.tfe"
flatpak install --assumeyes --user flathub "io.github.vmkspv.netsleuth"
flatpak install --assumeyes --user flathub "io.github.zarestia_dev.rclone-manager"
flatpak install --assumeyes --user flathub "it.fabiodistasio.AntaresSQL"
flatpak install --assumeyes --user flathub "it.mijorus.gearlever"
flatpak install --assumeyes --user flathub "me.iepure.devtoolbox"
flatpak install --assumeyes --user flathub "net.code_industry.MasterPDFEditor"
flatpak install --assumeyes --user flathub "net.portswigger.BurpSuite-Community"
flatpak install --assumeyes --user flathub "org.freac.freac"
flatpak install --assumeyes --user flathub "org.gnome.Firmware"
flatpak install --assumeyes --user flathub "org.gnome.GHex"
flatpak install --assumeyes --user flathub "org.gnome.dspy"
flatpak install --assumeyes --user flathub "org.gramps_project.Gramps"
flatpak install --assumeyes --user flathub "org.kde.CrowTranslate"
flatpak install --assumeyes --user flathub "org.kde.kgeotag"
flatpak install --assumeyes --user flathub "org.librepcb.LibrePCB"
